// Application Action Constants
export const APP_ACTIONS = {
  // User Profile
  LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_COINS: 'UPDATE_COINS',
  UPDATE_LEVEL: 'UPDATE_LEVEL',
  UPDATE_STREAK: 'UPDATE_STREAK',
  
  // Quiz State
  START_QUIZ: 'START_QUIZ',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  COMPLETE_QUIZ: 'COMPLETE_QUIZ',
  RESET_QUIZ: 'RESET_QUIZ',
  
  // Learning Progress
  COMPLETE_MODULE: 'COMPLETE_MODULE',
  UPDATE_READING_PROGRESS: 'UPDATE_READING_PROGRESS',
  
  // Game State
  UPDATE_GAME_STATS: 'UPDATE_GAME_STATS',
  UNLOCK_ACHIEVEMENT: 'UNLOCK_ACHIEVEMENT',
  
  // UI State
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SET_MODAL: 'SET_MODAL',
  
  // Navigation
  NAVIGATE_TO: 'NAVIGATE_TO'
} as const;